# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}. 

title: Life on Wheels
email: isaachanstar@gmail.com
full_description: >-
  Life on Wheels! As a professional software engineer specializing 
  in Enterprise Architecture, Cloud Native, DevOps, and AI/ML, 
  I blend technical expertise with my personal passions. At home, 
  I'm a devoted father and husband. On the track, I'm an adrenaline-fueled 
  car racer. I'm dedicated to sharing insights from my diverse 
  experiences and am a lifelong learner at heart. Join me in this 
  exhilarating journey through tech, family, and the thrill of racing.
description: >- # this means to ignore newlines until "baseurl:"
  Explore the dual thrills of software engineering and car racing 
  in my blog 'Life on Wheels.' Dive into a world where cutting-edge 
  tech meets the exhilaration of the race track.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  isaachan

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
